"""
Utility functions for frozen lake.
"""

import numpy as np


def random_deterministic_policy(env):
    """Generates a random deterministic policy for a given environment.

    Args:
        env: The Gym environment to generate the policy for. It should have
            observation_space and action_space attributes.

    Returns:
        np.ndarray: A one-hot encoded policy matrix of shape (obs_space.n, action_space.n).
    """
    obs_space = env.observation_space
    action_space = env.action_space
    policy = np.random.multinomial(
        1, [1 / action_space.n] * action_space.n, size=obs_space.n
    )

    return policy


def random_stochastic_policy(env):
    """Generates a random stochastic policy for a given environment.

    The policy is generated by applying a softmax transformation to randomly sampled values.

    Args:
        env: The Gym environment to generate the policy for. It should have
            observation_space and action_space attributes.

    Returns:
        np.ndarray: A probability distribution matrix of shape (obs_space.n, action_space.n).
    """
    x = np.random.random((env.observation_space.n, env.action_space.n))
    softmax_x = np.exp(x) / np.sum(np.exp(x), axis=1, keepdims=True)

    return softmax_x


# optimal policy for standard 4x4 non-slippery
OPTIMAL_FROZEN_LAKE_POLICY = np.array(
    [
        [0, 0, 1, 0],
        [0, 0, 1, 0],
        [0, 1, 0, 0],
        [1, 0, 0, 0],
        [0, 1, 0, 0],
        [1, 0, 0, 0],
        [0, 1, 0, 0],
        [1, 0, 0, 0],
        [0, 0, 1, 0],
        [0, 0, 1, 0],
        [0, 1, 0, 0],
        [1, 0, 0, 0],
        [1, 0, 0, 0],
        [0, 0, 1, 0],
        [0, 0, 1, 0],
        [1, 0, 0, 0],
    ]
)
